- name: golang-security-action
  # You may pin to the exact commit or the version.
  # uses: Ynniss/golang-security-action@cb6559433c01cbe2c6d357d7c731eefe03641ad3
  uses: Ynniss/golang-security-action@v0.1.3
  with:
    # path to the config file gosec will use
    CONF_PATH: # optional
    # path to the code that will be analyzed
    CODE_PATH: # default is .
